# Shell variables
# Generated by 'wal'
wallpaper='/home/alexis/Pictures/Wallpapers/8.04.png'

# Special
background='#311200'
foreground='#dbbb97'
cursor='#dbbb97'

# Colors
color0='#311200'
color1='#9A5222'
color2='#A65A27'
color3='#B4652E'
color4='#CF6B1B'
color5='#C55736'
color6='#A37353'
color7='#dbbb97'
color8='#998269'
color9='#9A5222'
color10='#A65A27'
color11='#B4652E'
color12='#CF6B1B'
color13='#C55736'
color14='#A37353'
color15='#dbbb97'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
